### ISSUE TITLE
Edit link doesn't work in Umbraco 7

### ISSUE THREAD

**Issue by greystate** [greystate/LatestEditsDashboard#3]
Though not officially supported, the package seems to be usable in Umbraco 7 as well, though the "Edit" links needs to be updated to use V7 link structure, as discussed in [this Forum post](https://our.umbraco.org/projects/backoffice-extensions/latest-edits-dashboard/latestedits-forum/63825-Link-to-edit-node-in-Umbraco-7?p=0#comment215353)

Should be able to detect Umbraco version and create the correct link

**Comment by leekelleher** [comment]
I'm wondering how we could detect v7 in XSLT... maybe if the `JsonToXml` extension is there?

    function-available('umb:JsonToXml')

**Comment by greystate** [comment]
That's one way - that was introduced somewhere around 7.x, right?

Another one would be to check the Umbraco version (w00t? :-)

```xslt
<xsl:variable name="umbVersion" select="document('../Web.config')/configuration/appSettings/add[@key = 'umbracoConfigurationStatus']/@value" />
```

(Which also shows how clownish that "config" XML file format is :-)

/Chriztian

**Comment by leekelleher** [comment]
`JsonToXml` was introduced for v7.0.0 (geek ref: [0c226d1](https://github.com/umbraco/Umbraco-CMS/commit/0c226d1a2c170e7f3888aae67dd3de85af9e2a79)).

The "Web.config" would future proof it (thinking v8+) ... but it feels overkill for such a simple value check.

**Comment by greystate** [comment]
:+1:
